version: '3.8'

services:
  web:
    build: .
    command: python -u app.py
    ports:
      - "4500:4500"
    volumes:
      - .:/python-docker
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://root:pass@db:27017/inventory_db?authSource=admin
    networks:
      - app-network

  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=inventory_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge